import random
monsterNames = [
    "Aarakocra",
    "Abjurer",
    "Aboleth",
    "Abominable Yeti",
    "Acolyte",
    "Adult Black Dragon",
    "Adult Blue Dracolich",
    "Adult Blue Dragon",
    "Adult Brass Dragon",
    "Adult Bronze Dragon",
    "Adult Copper Dragon",
    "Adult Gold Dragon",
    "Adult Green Dragon",
    "Adult Red Dragon",
    "Adult Silver Dragon",
    "Adult White Dragon",
    "Air Elemental",
    "Alhoon",
    "Allosaurus",
    "Ancient Black Dragon",
    "Ancient Blue Dragon",
    "Ancient Brass Dragon",
    "Ancient Bronze Dragon",
    "Ancient Copper Dragon",
    "Ancient Gold Dragon",
    "Ancient Green Dragon",
    "Ancient Red Dragon",
    "Ancient Silver Dragon",
    "Ancient White Dragon",
    "Androsphinx",
    "Animated Armor",
    "Ankheg",
    "Ankylosaurus",
    "Annis Hag",
    "Ape",
    "Apprentice Wizard",
    "Arcanaloth",
    "Archdruid",
    "Archer",
    "Archmage",
    "Assassin",
    "Aurochs",
    "Awakened Shrub",
    "Awakened Tree",
    "Axe Beak",
    "Azer",
    "Babau",
    "Baboon",
    "Badger",
    "Balor",
    "Banderhobb",
    "Bandit",
    "Bandit Captain",
    "Banshee",
    "Barbed Devil",
    "Bard",
    "Barghest",
    "Barlgura",
    "Basilisk",
    "Bat",
    "Bearded Devil",
    "Behir",
    "Beholder",
    "Beholder Zombie",
    "Berserker",
    "Bheur Hag",
    "Black Bear",
    "Black Dragon Wyrmling",
    "Black Pudding",
    "Blackguard",
    "Blink Dog",
    "Blood Hawk",
    "Blue Dragon Wyrmling",
    "Blue Slaad",
    "Boar",
    "Bodak",
    "Boggle",
    "Bone Devil",
    "Bone Naga",
    "Brass Dragon Wyrmling",
    "Bronze Dragon Wyrmling",
    "Brown Bear",
    "Bugbear",
    "Bugbear Chief",
    "Bulette",
    "Bullywug",
    "Cambion",
    "Camel",
    "Carrion Crawler",
    "Cat",
    "Catoblepas",
    "Cave Fisher",
    "Centaur",
    "Chain Devil",
    "Champion",
    "Chasme",
    "Chimera",
    "Chitine",
    "Choldrith",
    "Chuul",
    "Clay Golem",
    "Cloaker",
    "Cloud Giant",
    "Cloud Giant Smiling One",
    "Cockatrice",
    "Commoner",
    "Conjurer",
    "Constrictor Snake",
    "Copper Dragon Wyrmling",
    "Couatl",
    "Cow",
    "Crab",
    "Cranium Rat",
    "Crawling Claw",
    "Crocodile",
    "Cult Fanatic",
    "Cultist",
    "Cyclops",
    "Dao",
    "Darkling",
    "Darkling Elder",
    "Darkmantle",
    "Death Dog",
    "Death Kiss",
    "Death Knight",
    "Death Slaad",
    "Death Tyrant",
    "Deep Gnome (Svirfneblin)",
    "Deep Scion",
    "Deer",
    "Demilich",
    "Deva",
    "Devourer",
    "Dire Wolf",
    "Displacer Beast",
    "Diviner",
    "Djinni",
    "Dolphin",
    "Doppelganger",
    "Draegloth",
    "Draft Horse",
    "Dragon Turtle",
    "Dretch",
    "Drider",
    "Drow",
    "Drow Elite Warrior",
    "Drow Mage",
    "Drow Priestress of Lolth",
    "Druid",
    "Dryad",
    "Duergar",
    "Duodrone",
    "Dust Mephit",
    "Eagle",
    "Earth Elemental",
    "Efreeti",
    "Elder Brain",
    "Elephant",
    "Elk",
    "Empyrean",
    "Enchanter",
    "Erinyes",
    "Ettercap",
    "Ettin",
    "Evoker",
    "Faerie Dragon",
    "Fire Elemental",
    "Fire Giant",
    "Fire Giant Dreadnought",
    "Fire Snake",
    "Firenewt Warlock of Imix",
    "Firenewt Warrior",
    "Flail Snail",
    "Flameskull",
    "Flesh Golem",
    "Flind",
    "Flumph",
    "Flying Snake",
    "Flying Sword",
    "Fomorian",
    "Frog",
    "Froghemoth",
    "Frost Giant",
    "Frost Giant Everlasting One",
    "Galeb Duhr",
    "Gargoyle",
    "Gas Spore",
    "Gauth",
    "Gazer",
    "Gelatinous Cube",
    "Ghast",
    "Ghost",
    "Ghoul",
    "Giant Ape",
    "Giant Badger",
    "Giant Bat",
    "Giant Boar",
    "Giant Centipede",
    "Giant Constrictor Snake",
    "Giant Crab",
    "Giant Crocodile",
    "Giant Eagle",
    "Giant Elk",
    "Giant Fire Beetle",
    "Giant Frog",
    "Giant Goat",
    "Giant Hyena",
    "Giant Lizard",
    "Giant Octopus",
    "Giant Owl",
    "Giant Poisonous Snake",
    "Giant Rat",
    "Giant Scorpion",
    "Giant Sea Horse",
    "Giant Shark",
    "Giant Spider",
    "Giant Strider",
    "Giant Toad",
    "Giant Vulture",
    "Giant Wasp",
    "Giant Weasel",
    "Giant Wolf Spider",
    "Gibbering Mouther",
    "Girallon",
    "Githyanki Knight",
    "Githyanki Warrior",
    "Githzerai Monk",
    "Githzerai Zerth",
    "Glabrezu",
    "Gladiator",
    "Gnoll",
    "Gnoll Fang of Yeenoghu",
    "Gnoll Flesh Gnawer",
    "Gnoll Hunter",
    "Gnoll Pack Lord",
    "Gnoll Witherling",
    "Goat",
    "Goblin",
    "Goblin Boss",
    "Gold Dragon Wyrmling",
    "Gorgon",
    "Goristro",
    "Gray Ooze",
    "Gray Slaad",
    "Green Dragon Wyrmling",
    "Green Hag",
    "Green Slaad",
    "Grell",
    "Grick",
    "Grick alpha",
    "Griffon",
    "Grimlock",
    "Grung",
    "Grung Elite Warrior",
    "Grung Wildling",
    "Guard",
    "Guard Drake",
    "Guardian Naga",
    "Gynosphinx",
    "Half-Ogre",
    "Half-Red Dragon Veteran",
    "Harpy",
    "Hawk",
    "Hell Hound",
    "Helmed Horror",
    "Hezrou",
    "Hill Giant",
    "Hippogriff",
    "Hobgoblin",
    "Hobgoblin Captain",
    "Hobgoblin Devastator",
    "Hobgoblin Iron Shadow",
    "Hobgoblin Warlord",
    "Homunculus",
    "Hook Horror",
    "Horned Devil",
    "Hunter Shark",
    "Hydra",
    "Hyena",
    "Ice Devil",
    "Ice Mephit",
    "Illusionist",
    "Imp",
    "Intellect Devourer",
    "Invisible Stalker",
    "Iron Golem",
    "Jackal",
    "Jackalwere",
    "Kenku",
    "Ki-rin",
    "Killer Whale",
    "Knight",
    "Kobold",
    "Kobold Dragonshield",
    "Kobold Inventor",
    "Kobold Scale Sorcerer",
    "Korred",
    "Kraken",
    "Kraken Priest",
    "Kuo-toa",
    "Kuo-toa Archpriest",
    "Kuo-toa Whip",
    "Lamia",
    "Lemure",
    "Leucrotta",
    "Lich",
    "Lion",
    "Lizard",
    "Lizard KingQueen",
    "Lizardfolk",
    "Lizardfolk Shaman",
    "Mage",
    "Magma Mephit",
    "Magmin",
    "Mammoth",
    "Manes",
    "Manticore",
    "Marid",
    "Marilith",
    "Martial Arts Adept",
    "Master Thief",
    "Mastiff",
    "Maw Demon",
    "Medusa",
    "Meenlock",
    "Merfolk",
    "Merrow",
    "Mezzoloth",
    "Mimic",
    "Mind Flayer",
    "Mindwitness",
    "Minotaur",
    "Minotaur Skeleton",
    "Monodrone",
    "Morkoth",
    "Mouth of Grolantor",
    "Mud Mephit",
    "Mule",
    "Mummy",
    "Mummy Lord",
    "Myconid adult",
    "Myconid Sovereign",
    "Myconid sprout",
    "Nalfeshnee",
    "Necromancer",
    "Needle Blight",
    "Neogi",
    "Neogi Hatchling",
    "Neogi Master",
    "Neothelid",
    "Night Hag",
    "Nightmare",
    "Nilbog",
    "Noble",
    "Nothic",
    "Nycaloth",
    "Ochre Jelly",
    "Octopus",
    "Ogre",
    "Ogre Zombie",
    "Oni",
    "Orc",
    "Orc Blade of Ilneval",
    "Orc Claw of Luthic",
    "Orc Eye of Gruumsh",
    "Orc Hand of Yurtrus",
    "Orc Red Fang of Shargaas",
    "Orc War Chief",
    "Orog",
    "Otyugh",
    "Owl",
    "Owlbear",
    "Panther",
    "Pegasus",
    "Pentadrone",
    "Peryton",
    "Phase Spider",
    "Piercer",
    "Pit Fiend",
    "Pixie",
    "Planetar",
    "Plesiosaurus",
    "Poisonous Snake",
    "Polar Bear",
    "Pony",
    "Priest",
    "Pseudodragon",
    "Pteranodon",
    "Purple Worm",
    "Quadrone",
    "Quaggoth",
    "Quaggoth spore servant",
    "Quasit",
    "Quetzalcoatlus",
    "Quickling",
    "Quipper",
    "Rakshasa",
    "Rat",
    "Raven",
    "Red Dragon Wyrmling",
    "Red Slaad",
    "Redcap",
    "Reef Shark",
    "Remorhaz",
    "Revenant",
    "Rhinoceros",
    "Riding Horse",
    "Roc",
    "Roper",
    "Rug of Smothering",
    "Rust Monster",
    "Saber-Toothed Tiger",
    "Sahuagin",
    "Sahuagin Baron",
    "Sahuagin Priestess",
    "Salamander",
    "Satyr",
    "Scarecrow",
    "Scorpion",
    "Scout",
    "Sea Hag",
    "Sea Horse",
    "Sea Spawn",
    "Shadow",
    "Shadow Demon",
    "Shadow Mastiff",
    "Shambling Mound",
    "Shield Guardian",
    "Shoosuva",
    "Shrieker",
    "Silver Dragon Wyrmling",
    "Skeleton",
    "Slaad Tadpole",
    "Slithering Tracker",
    "Smoke Mephit",
    "Solar",
    "Spawn of Kyuss",
    "Spectator",
    "Specter",
    "Spider",
    "Spined Devil",
    "Spirit Naga",
    "Sprite",
    "Spy",
    "Steam Mephit",
    "Stirge",
    "Stone Giant",
    "Stone Giant Dreamwalker",
    "Stone Golem",
    "Storm Giant",
    "Storm Giant Quintessent",
    "Succubus",
    "Swarm of Bats",
    "Swarm of Cranium Rats",
    "Swarm of Insects",
    "Swarm of Poisonous Snakes",
    "Swarm of Quippers",
    "Swarm of Rats",
    "Swarm of Ravens",
    "Swarm of Rot Grubs",
    "Swashbuckler",
    "Tanarukk",
    "Tarrasque",
    "Thorny",
    "Thri-kreen",
    "Thug",
    "Tiger",
    "Tlincalli",
    "Transmuter",
    "Trapper",
    "Treant",
    "Tribal Warrior",
    "Triceratops",
    "Tridrone",
    "Troglodyte",
    "Troll",
    "Twig Blight",
    "Tyrannosaurus Rex",
    "Ulitharid",
    "Ultroloth",
    "Umber Hulk",
    "Unicorn",
    "Vampire",
    "Vampire Spawn",
    "Vargouille",
    "Vegepygmy",
    "Vegepygmy Chief",
    "Velociraptor",
    "Veteran",
    "Vine Blight",
    "Violet Fungus",
    "Vrock",
    "Vulture",
    "War priest",
    "Warhorse",
    "Warhorse Skeleton",
    "Warlock of the Archfey",
    "Warlock of the fiend",
    "Warlock of the Great Old One",
    "Warlord",
    "Water Elemental",
    "Water Weird",
    "Weasel",
    "Werebear",
    "Wereboar",
    "Wererat",
    "Weretiger",
    "Werewolf",
    "White Dragon Wyrmling",
    "Wight",
    "Will-o'-Wisp",
    "Winged Kobold",
    "Winter Wolf",
    "Wolf",
    "Wood Woad",
    "Worg",
    "Wraith",
    "Wyvern",
    "Xorn",
    "Xvart",
    "Xvart Warlock of Raxivort",
    "Yeth Hound",
    "Yeti",
    "Yochlol",
    "Young Black Dragon",
    "Young Blue Dragon",
    "Young Brass Dragon",
    "Young Bronze Dragon",
    "Young Copper Dragon",
    "Young Gold Dragon",
    "Young Green Dragon",
    "Young Red Dragon",
    "Young Red Shadow Dragon",
    "Young Remorhaz",
    "Young Silver Dragon",
    "Young White Dragon",
    "Yuan-ti Abomination",
    "Yuan-ti Anathema",
    "Yuan-ti Broodguard",
    "Yuan-ti Malison",
    "Yuan-ti Mind Whisperer",
    "Yuan-ti Nightmare Speaker",
    "Yuan-ti Pit Master",
    "Yuan-ti Pureblood",
    "Zombie"
]

adjectives = [
    "Abrasive",
    "Abrupt",
    "Absent-minded",
    "Abusive",
    "Accepting",
    "Accommodating",
    "Accomplished",
    "Action oriented",
    "Adamant",
    "Adaptable",
    "Addict",
    "ADHD",
    "Adulterer",
    "Adventurous",
    "Affable",
    "Affectionate",
    "Afraid",
    "Afraid of commitment",
    "Afraid of ghosts",
    "Aggressive",
    "Agnostic",
    "Agonized",
    "Agreeable",
    "Alcoholic",
    "Alert",
    "Alluring",
    "Aloof",
    "Altruistic",
    "Always late",
    "Amateurish demeanor",
    "Ambiguous",
    "Ambitious",
    "Ambivalent",
    "Amiable",
    "Amused",
    "Amusing",
    "Analytical",
    "Angry",
    "Animated",
    "Annoyed",
    "Annoying",
    "Antagonistic",
    "Anti-intellectual",
    "Anti-social",
    "Anxious",
    "Apathetic",
    "Apologetic",
    "Appreciative",
    "Apprehensive",
    "Approachable",
    "Arbitrary",
    "Argumentative",
    "Aristocratic",
    "Arrogant",
    "Art collector",
    "Articulate",
    "Artistic",
    "Artless",
    "Ashamed",
    "Aspiring",
    "Assertive",
    "Astonished",
    "Astounded",
    "Astute",
    "Attentive",
    "Attentive to others",
    "Audacious",
    "Austere",
    "Authoritarian",
    "Authoritative",
    "Autocratic",
    "Avoids conflict",
    "Aware of own limitations",
    "Awed",
    "Awful",
    "Awkward",
    "Babbling",
    "Babyish",
    "Backstabber",
    "Bashful",
    "Belligerent",
    "Benevolent",
    "Betrayed",
    "Bewildered",
    "Bewitching",
    "Biter",
    "Bitter",
    "Blames others",
    "Blasé",
    "Blissful",
    "Blowhard",
    "Boastful",
    "Boisterous",
    "Bold",
    "Boorish",
    "Bored",
    "Boring",
    "Bossy",
    "Boundless",
    "Bragging",
    "Brainy",
    "Brash",
    "Bratty",
    "Brave",
    "Brazen",
    "Bright",
    "Brilliant",
    "Broad-minded",
    "Brotherly",
    "Brutish",
    "Bubbly",
    "Bully",
    "Burdened",
    "Busy",
    "Calculating",
    "Callous",
    "Calm",
    "Candid",
    "Capable",
    "Capricious",
    "Captivated",
    "Carefree",
    "Careful",
    "Careless",
    "Careless of social rules",
    "Caring",
    "Caustic",
    "Cautious",
    "Changeable",
    "Charismatic",
    "Charitable",
    "Charming",
    "Chaste",
    "Chatty",
    "Cheat",
    "Cheerful",
    "Cheerless",
    "Childish",
    "Chivalrous",
    "Civilised",
    "Classy",
    "Clean",
    "Clever",
    "Close",
    "Closed",
    "Clumsy",
    "Coarse",
    "Cocky",
    "Coherent",
    "Cold",
    "Cold hearted",
    "Combative",
    "Comfortable",
    "Committed",
    "Communicative",
    "Compassionate",
    "Competent",
    "Competitive",
    "Complacent",
    "Compliant",
    "Compulsive",
    "Compulsive liar",
    "Conceited",
    "Concerned",
    "Concrete thinking",
    "Condemned",
    "Condescending",
    "Confident",
    "Conformist",
    "Confused",
    "Congenial",
    "Connoisseur of good drink",
    "Connoisseur of good food",
    "Conscientious",
    "Conservative",
    "Considerate",
    "Consistent",
    "Conspicuous",
    "Conspiracy theorist",
    "Constricting",
    "Constructive",
    "Content",
    "Contented",
    "Contrarian",
    "Contrary",
    "Contrite",
    "Controlling",
    "Conventional",
    "Conversational",
    "Cool",
    "Cooperative",
    "Coquettish",
    "Cosmopolitan",
    "Courageous",
    "Courteous",
    "Covetous",
    "Cowardly",
    "Cowering",
    "Coy",
    "Crabby",
    "Crafty",
    "Cranky",
    "Crazy",
    "Creative",
    "Credible",
    "Creepy",
    "Critical",
    "Cross",
    "Crude",
    "Cruel",
    "Crushed",
    "Cuddly",
    "Culpable",
    "Cultured",
    "Cunning",
    "Curious",
    "Cutthroat",
    "Cynical",
    "Dainty",
    "Dangerous",
    "Daredevil",
    "Daring",
    "Dark",
    "Dashing",
    "Dauntless",
    "Dazzling",
    "Debonair",
    "Deceitful",
    "Deceiving",
    "Decent",
    "Decisive",
    "Decorous",
    "Dedicated",
    "Defeated",
    "Deferential",
    "Defiant",
    "Delegates authority",
    "Deliberate",
    "Deliberative",
    "Delicate",
    "Delighted",
    "Delightful",
    "Delusional about own skills",
    "Demanding",
    "Demonic",
    "Dependable",
    "Dependent",
    "Depraved",
    "Depressed",
    "Depressive",
    "Deranged",
    "Desirous",
    "Despairing",
    "Despicable",
    "Despondent",
    "Destructive",
    "Detached",
    "Detail-oriented",
    "Determined",
    "Develops close friendships",
    "Devilish",
    "Devious",
    "Devoted",
    "Devout",
    "Dictatorial",
    "Diffident",
    "Dignified",
    "Diligent",
    "Diminished",
    "Diplomatic",
    "Direct",
    "Directionless",
    "Disaffected",
    "Disagreeable",
    "Discerning",
    "Disciplined",
    "Discontented",
    "Discouraged",
    "Discreet",
    "Disgusting",
    "Dishonest",
    "Disillusioned",
    "Disinterested",
    "Disloyal",
    "Dismayed",
    "Disorderly",
    "Disorganized",
    "Disparaging",
    "Disregards rules",
    "Disrespectful",
    "Dissatisfied",
    "Dissident",
    "Dissolute",
    "Distant",
    "Distracted",
    "Distraught",
    "Distressed",
    "Distrustful",
    "Disturbed",
    "Divided",
    "Docile",
    "Does what is convenient",
    "Does what is necessary or right",
    "Dogmatic",
    "Dominant",
    "Domineering",
    "Dorky",
    "Doubtful",
    "Dowdy",
    "Downtrodden",
    "Draconian",
    "Dramatic",
    "Dreamer",
    "Dreamy",
    "Dreary",
    "Driven",
    "Drug addict",
    "Drunk",
    "Dubious",
    "Dull",
    "Dumb",
    "Dutiful",
    "Dynamic",
    "Eager",
    "Easily embarrassed",
    "Easily led",
    "Easily upset",
    "Easygoing",
    "Eccentric",
    "Ecstatic",
    "Educated",
    "Effervescent",
    "Efficient",
    "Egocentric",
    "Egotistic",
    "Egotistical",
    "Elated",
    "Electrified",
    "Eloquent",
    "Elusive",
    "Embarrassed",
    "Embittered",
    "Embraces change",
    "Eminent",
    "Emotional",
    "Emotionally stable",
    "Empathetic",
    "Empty",
    "Enchanted",
    "Enchanting",
    "Encouraging",
    "Enduring",
    "Energetic",
    "Engaging",
    "Enigmatic",
    "Enjoys a good argument",
    "Enjoys a good brawl",
    "Enjoys a little friendly competition",
    "Enterprising",
    "Entertaining",
    "Enthusiastic",
    "Entrepreneurial",
    "Envious",
    "Equable",
    "Erratic",
    "Ethical",
    "Evasive",
    "Evil",
    "Exacting",
    "Exasperated",
    "Excellent",
    "Excessive",
    "Excitable",
    "Excited",
    "Exclusive",
    "Exhausted",
    "Expansive",
    "Expedient",
    "Experimental",
    "Expert",
    "Expressive",
    "Extravagant",
    "Extraverted",
    "Extreme",
    "Exuberant",
    "Fabulous",
    "Faces reality",
    "Facetious",
    "Faded",
    "Failure",
    "Fair",
    "Faith in oneself",
    "Faith in others",
    "Faith in self",
    "Faithful",
    "Faithless",
    "Fake",
    "Fanatical",
    "Fanciful",
    "Fantastic",
    "Fascinated",
    "Fast learner",
    "Fastidious",
    "Fatalistic",
    "Fatigued",
    "Fawning",
    "Fearful",
    "Fearless",
    "Feisty",
    "Ferocious",
    "Fidgety",
    "Fierce",
    "Fiery",
    "Fighter",
    "Fine",
    "Finicky",
    "Fitness fanatic",
    "Flagging",
    "Flakey",
    "Flamboyant",
    "Flashy",
    "Fleeting",
    "Flexible",
    "Flighty",
    "Flippant",
    "Flirtatious",
    "Flirty",
    "Flustered",
    "Focused",
    "Follower",
    "Follows rules",
    "Foolhardy",
    "Foolish",
    "Forceful",
    "Forgetful",
    "Forgiving",
    "Formal",
    "Forthright",
    "Fortunate",
    "Foul",
    "Fragile",
    "Fragmented",
    "Frank",
    "Frantic",
    "Frazzled",
    "Free of guilt",
    "Free thinking",
    "Fresh",
    "Fretful",
    "Friendly",
    "Frightened",
    "Frigid",
    "Frugal",
    "Frustrated",
    "Fuddy duddy",
    "Fun",
    "Fun loving",
    "Fun to be around",
    "Funny",
    "Furious",
    "Furtive",
    "Fussy",
    "Gabby",
    "Garrulous",
    "Gaudy",
    "Generous",
    "Genial",
    "Gentle",
    "Genuine",
    "Giddy",
    "Giggly",
    "Gives others their freedom",
    "Gives up easily",
    "Giving",
    "Glad",
    "Glamorous",
    "Gloomy",
    "Glorious",
    "Glum",
    "Glutton",
    "Gluttonous",
    "Goal orientated",
    "Good",
    "Good communicator",
    "Good listener",
    "Good-natured",
    "Good-spirited",
    "Goofy",
    "Graceful",
    "Gracious",
    "Grandiose",
    "Grateful",
    "Gratified",
    "Greedy",
    "Gregarious",
    "Grief",
    "Grieving",
    "Groovy",
    "Grotesque",
    "Grouchy",
    "Grounded",
    "Group-oriented",
    "Growly",
    "Gruesome",
    "Gruff",
    "Grumpy",
    "Guarded",
    "Guileless",
    "Guilt prone",
    "Guilt ridden",
    "Guilty",
    "Gullible",
    "Haggard",
    "Haggling",
    "Handsome",
    "Happy",
    "Happy go lucky",
    "Hard",
    "Hard working",
    "Harmonious",
    "Harried",
    "Harsh",
    "Has a vision for the future",
    "Has achieved many things in life",
    "Has clear goals",
    "Has good taste",
    "Hasn't achieved much in life",
    "Hassled",
    "Hateful",
    "Haughty",
    "Haunted by a ghost",
    "Heart broken",
    "Heartless",
    "Heavenly",
    "Heavy hearted",
    "Hedonistic",
    "Helpful",
    "Helpless",
    "Heroic",
    "Hesitant",
    "High",
    "High energy",
    "High self esteem",
    "High social status",
    "Hilarious",
    "Hobbyist",
    "Holy",
    "Homeless",
    "Homesick",
    "Honest",
    "Honor bound",
    "Honorable",
    "Hopeful",
    "Hopeless",
    "Horrible",
    "Hospitable",
    "Hostile",
    "Hot headed",
    "Huffy",
    "Humble",
    "Humorous",
    "Hurt",
    "Hypocritical",
    "Hysterical",
    "Ignorant",
    "Ignored",
    "Ill-bred",
    "Imaginative",
    "Immaculate",
    "Immature",
    "Immobile",
    "Immodest",
    "Impartial",
    "Impatient",
    "Impeccable",
    "Imperial",
    "Impersonal",
    "Impolite",
    "Impotent",
    "Impoverished",
    "Impractical",
    "Impressed",
    "Improves self",
    "Impudent",
    "Impulsive",
    "In harmony",
    "Inactive",
    "Incoherent",
    "Incompetent",
    "Inconsiderate",
    "Inconsistent",
    "Indecisive",
    "Independent",
    "Indifferent",
    "Indiscrete",
    "Indiscriminate",
    "Individualistic",
    "Indolent",
    "Indulgent",
    "Industrious",
    "Inefficient",
    "Inept",
    "Infantile",
    "Infatuated",
    "Inflexible",
    "Informed",
    "Infuriated",
    "Inherited success",
    "Inhibited",
    "Inhumane",
    "Inimitable",
    "Innocent",
    "Inquisitive",
    "Insane",
    "Insecure",
    "Insensitive",
    "Insightful",
    "Insincere",
    "Insipid",
    "Insistent",
    "Insolent",
    "Insouciant",
    "Inspired",
    "Instinctive",
    "Insulting",
    "Intellectual",
    "Intelligent",
    "Intense",
    "Interested",
    "Interrupting",
    "Intimidated",
    "Intimidating",
    "Intolerant",
    "Intrepid",
    "Introspective",
    "Introverted",
    "Intuitive",
    "Inventive",
    "Involved",
    "Irresolute",
    "Irresponsible",
    "Irreverent",
    "Irritable",
    "Irritating",
    "Isolated",
    "Jackass",
    "Jaded",
    "Jealous",
    "Jittery",
    "Joking",
    "Jolly",
    "Jovial",
    "Joyful",
    "Joyous",
    "Judgmental",
    "Jumpy",
    "Just",
    "Keen",
    "Kenderish",
    "Kind",
    "Kind hearted",
    "Kittenish",
    "Knowledgeable",
    "Lackadaisical",
    "Lacking",
    "Laconic",
    "Languid",
    "Lascivious",
    "Late",
    "Lax",
    "Lazy",
    "Leader",
    "Leaves things unfinished",
    "Lecherous",
    "Lethargic",
    "Level",
    "Lewd",
    "Liar",
    "Liberal",
    "Licentious",
    "Light-hearted",
    "Likeable",
    "Likes people",
    "Limited",
    "Lineat",
    "Lingering",
    "Lively",
    "Logical",
    "Lonely",
    "Longing",
    "Loquacious",
    "Lordly",
    "Loud",
    "Loudmouth",
    "Lovable",
    "Love",
    "Lovely",
    "Lover, not a fighter",
    "Loves challenge",
    "Loving",
    "Low confidence",
    "Low drive",
    "Low social status",
    "Lowly",
    "Loyal",
    "Loyal to boss",
    "Loyal to community",
    "Loyal to family",
    "Loyal to friends",
    "Lucky",
    "Lunatic",
    "Lusty",
    "Lying",
    "Macho",
    "Mad",
    "Malevolent",
    "Malice",
    "Malicious",
    "Maniacal",
    "Manic",
    "Manipulative",
    "Mannered",
    "Mannerly",
    "Masochistic",
    "Materialistic",
    "Matronly",
    "Matter-of-fact",
    "Mature",
    "Maudlin",
    "Mean",
    "Mean-spirited",
    "Meek",
    "Megalomaniac",
    "Melancholy",
    "Melodramatic",
    "Mentally slow",
    "Merciful",
    "Mercurial",
    "Messy",
    "Meticulous",
    "Mild",
    "Mischievous",
    "Miserable",
    "Miserly",
    "Mistrusting",
    "Modern",
    "Modest",
    "Moody",
    "Moping",
    "Moralistic",
    "Morbid",
    "Motherly",
    "Motivated",
    "Muddled goals",
    "Murderer",
    "Mysterious",
    "Mystical",
    "Nagging",
    "Naive",
    "Narcissistic",
    "Narrow-minded",
    "Nasty",
    "Natural leader",
    "Naughty",
    "Neat",
    "Needs social approval",
    "Needy",
    "Negative",
    "Negligent",
    "Nervous",
    "Neurotic",
    "Never gives up",
    "Never hungry",
    "Nibbler",
    "Nice",
    "Night owl",
    "Nihilistic",
    "Nit picker",
    "No purpose",
    "No self confidence",
    "No-nonsense",
    "Noble",
    "Noisy",
    "Non-committing",
    "Nonchalant",
    "Nonconforming",
    "Nostalgic",
    "Nosy",
    "Not trustworthy",
    "Nuanced",
    "Nuisance",
    "Nurturing",
    "Nut",
    "Obedient",
    "Obliging",
    "Oblivious",
    "Obnoxious",
    "Obscene",
    "Obsequious",
    "Observant",
    "Obsessed",
    "Obsessive about something",
    "Obstinate",
    "Odd",
    "Odious",
    "Open",
    "Open to change",
    "Open-minded",
    "Opinionated",
    "Opportunistic",
    "Oppositional",
    "Optimistic",
    "Orcish",
    "Orderly",
    "Organized",
    "Ornery",
    "Ossified",
    "Ostentatious",
    "Others can't be relied on",
    "Outgoing",
    "Outraged",
    "Outrageous",
    "Outspoken",
    "Over wrought",
    "Overbearing",
    "Overconfident",
    "Overwhelmed",
    "Overwhelming",
    "Paces",
    "Pacifistic",
    "Painstaking",
    "Pampered",
    "Panicked",
    "Panicky",
    "Paranoid",
    "Participating",
    "Particular",
    "Passionate",
    "Passive",
    "Passive-aggressive",
    "Pathetic",
    "Patient",
    "Patriotic",
    "Peaceful",
    "Penitent",
    "Pensive",
    "Perceptive",
    "Perfect",
    "Perfectionist",
    "Performer",
    "Persecuted",
    "Perserverant",
    "Perseveres",
    "Persevering",
    "Persistent",
    "Personable",
    "Persuasive",
    "Pert",
    "Perverse",
    "Perverted",
    "Pessimistic",
    "Petrified",
    "Petty",
    "Petulant",
    "Philanthropic",
    "Picky",
    "Pious",
    "Pitiful",
    "Pity",
    "Placid",
    "Playful",
    "Pleasant",
    "Pleased",
    "Pleasing",
    "Plotting",
    "Plucky",
    "Polished",
    "Polite",
    "Pompous",
    "Poor",
    "Poor communicator",
    "Poor listener",
    "Popular",
    "Positive",
    "Possessive",
    "Power-hungry",
    "Practical",
    "Precise",
    "Predictable",
    "Preoccupied",
    "Pressured",
    "Presumptuous",
    "Pretentious",
    "Pretty",
    "Prim",
    "Primitive",
    "Private",
    "Productive",
    "Profane",
    "Professional",
    "Professional demeanor",
    "Promiscuous",
    "Proper",
    "Prosaic",
    "Prosperous",
    "Protective",
    "Proud",
    "Prudent",
    "Psychotic",
    "Puckish",
    "Punctilious",
    "Punctual",
    "Purposeful",
    "Pushy",
    "Puzzled",
    "Quarrelsome",
    "Queer",
    "Quick",
    "Quick tempered",
    "Quiet",
    "Quirky",
    "Quitter",
    "Quixotic",
    "Radical",
    "Raging",
    "Rambunctious",
    "Random",
    "Rapturous",
    "Rash",
    "Rational",
    "Rawboned",
    "Reactionary",
    "Realistic",
    "Reasonable",
    "Reasoning",
    "Rebellious",
    "Recalcitrant",
    "Receptive",
    "Reckless",
    "Reclusive",
    "Refined",
    "Reflective",
    "Refreshed",
    "Regretful",
    "Rejected",
    "Rejects change",
    "Relaxed",
    "Relentless",
    "Relents",
    "Reliable",
    "Relieved",
    "Religious",
    "Reluctant",
    "Remorseful",
    "Remote",
    "Repugnant",
    "Repulsive",
    "Resentful",
    "Reserved",
    "Resilient",
    "Resolute",
    "Resourceful",
    "Respected in the community",
    "Respectful",
    "Respects experience",
    "Respects traditional ideas",
    "Responsible",
    "Responsive",
    "Restless",
    "Restrained",
    "Results-oriented",
    "Retiring",
    "Reverent",
    "Rewarded",
    "Rhetorical",
    "Rich",
    "Right",
    "Righteous",
    "Rigid",
    "Risk averse",
    "Risk-taking",
    "Robust and healthy",
    "Rogue",
    "Romantic",
    "Rough",
    "Rowdy",
    "Rude",
    "Rugged",
    "Rule-bound",
    "Rule-conscious",
    "Ruthless",
    "Sacrificing",
    "Sad",
    "Sadistic",
    "Safe",
    "Sagely",
    "Saintly",
    "Salient",
    "Sanctimonious",
    "Sanguine",
    "Sarcastic",
    "Sassy",
    "Satisfied",
    "Saucy",
    "Savage",
    "Savvy",
    "Scared",
    "Scarred",
    "Scary",
    "Scattered",
    "Scheming",
    "Scornful",
    "Scrawny",
    "Screwed up",
    "Scruffy",
    "Secretive",
    "Secure",
    "Sedate",
    "Seditious",
    "Seductive",
    "Sees the big picture",
    "Selective",
    "Self-absorbed",
    "Self-assured",
    "Self-blaming",
    "Self-centered",
    "Self-confident",
    "Self-conscious",
    "Self-controlling",
    "Self-deprecating",
    "Self-directed",
    "Self-disciplined",
    "Self-doubting",
    "Self-effacing",
    "Self-giving",
    "Self-indulgent",
    "Self-made",
    "Self-reliant",
    "Self-righteous",
    "Self-satisfied",
    "Self-serving",
    "Self-sufficient",
    "Selfish",
    "Selfless",
    "Senile",
    "Sense of duty",
    "Sensitive",
    "Sensual",
    "Sentimental",
    "Serene",
    "Serious",
    "Servile",
    "Settled",
    "Sexual",
    "Sexy",
    "Shallow",
    "Shameless",
    "Sharp",
    "Sharp-tongued",
    "Sharp-witted",
    "Sheepish",
    "Shiftless",
    "Shifty",
    "Shocked",
    "Short",
    "Short-tempered",
    "Shows initiative",
    "Shrewd",
    "Shy",
    "Silent",
    "Silky",
    "Silly",
    "Simple",
    "Simple-minded",
    "Sincere",
    "Sisterly",
    "Skeptical",
    "Skillful",
    "Sleazy",
    "Sloppy",
    "Slovenly",
    "Slow paced",
    "Sluggish",
    "Slutty",
    "Sly",
    "Small-minded",
    "Smart",
    "Smiling",
    "Smooth",
    "Sneaky",
    "Snob",
    "Snobbish",
    "Sociable",
    "Socially bold",
    "Socially precise",
    "Soft",
    "Soft-hearted",
    "Soft-spoken",
    "Solemn",
    "Solitary",
    "Solution-oriented",
    "Sophisticated",
    "Sore",
    "Sorrowful",
    "Sorry",
    "Sour",
    "Spendthrift",
    "Spiritual",
    "Spiteful",
    "Splendid",
    "Spoiled",
    "Spontaneous",
    "Sports fan",
    "Spunky",
    "Squeamish",
    "Staid",
    "Startled",
    "Stately",
    "Static",
    "Steadfast",
    "Steady",
    "Stern",
    "Stimulating",
    "Stingy",
    "Stoic",
    "Stoical",
    "Stolid",
    "Straight laced",
    "Straight-laced",
    "Straightforward",
    "Strange",
    "Stress free",
    "Stressed out",
    "Strict",
    "Strident",
    "Strong",
    "Strong nerves",
    "Strong willed",
    "Stubborn",
    "Studious",
    "Stunned",
    "Stupefied",
    "Stupid",
    "Suave",
    "Submissive",
    "Subtle",
    "Successful",
    "Successful in school",
    "Successful in work",
    "Succinct",
    "Suffering",
    "Sulky",
    "Sullen",
    "Sultry",
    "Supercilious",
    "Superstitious",
    "Supportive",
    "Sure",
    "Surly",
    "Suspicious",
    "Suspicious of strangers",
    "Sweet",
    "Sycophantic",
    "Sympathetic",
    "Systematic",
    "Taciturn",
    "Tacky",
    "Tactful",
    "Tactless",
    "Takes responsibility",
    "Talented",
    "Talkative",
    "Tardy",
    "Tasteful",
    "Telepathic",
    "Temperamental",
    "Temperate",
    "Tempted",
    "Tenacious",
    "Tender minded",
    "Tense",
    "Tentative",
    "Tenuous",
    "Terrible",
    "Terrified",
    "Testy",
    "Thankful",
    "Thankless",
    "Thick skinned",
    "Thief",
    "Thorough",
    "Thoughtful",
    "Thoughtless",
    "Threatened",
    "Threatening",
    "Thrifty",
    "Thrilled",
    "Thrillseeker",
    "Thwarted",
    "Tight",
    "Time driven",
    "Timid",
    "Tired",
    "Tireless",
    "Tiresome",
    "Toadying",
    "Tolerant",
    "Tolerates disorder",
    "Torpid",
    "Touchy",
    "Tough",
    "Tough-minded",
    "Traditional",
    "Traitorous",
    "Tranquil",
    "Treacherous",
    "Treasonous",
    "Tricky",
    "Tries to do everything",
    "Trivial",
    "Troubled",
    "Truculent",
    "Trusting",
    "Trustworthy",
    "Truthful",
    "Typical",
    "Tyrannical",
    "Unappreciative",
    "Unapproachable",
    "Unassuming",
    "Unaware of own limitations",
    "Unbending",
    "Unbiased",
    "Uncaring",
    "Uncommitted",
    "Uncommunicative",
    "Unconcerned",
    "Unconditional",
    "Uncontrolled",
    "Unconventional",
    "Uncooperative",
    "Uncoordinated",
    "Uncouth",
    "Undependable",
    "Understanding",
    "Undesirable",
    "Undisciplined",
    "Uneasy",
    "Uneducated",
    "Unenthusiastic",
    "Unexacting",
    "Unfeeling",
    "Unfocused",
    "Unforgiving",
    "Unfriendly",
    "Ungrateful",
    "Unhappy",
    "Unhelpful",
    "Uninhibited",
    "Unkind",
    "Unlucky",
    "Unmotivated",
    "Unpredictable",
    "Unprejudiced",
    "Unpretentious",
    "Unreasonable",
    "Unreceptive",
    "Unreliable",
    "Unresponsive",
    "Unrestrained",
    "Unruly",
    "Unscrupulous",
    "Unselfish",
    "Unsentimental",
    "Unsettled",
    "Unshakeable",
    "Unsure",
    "Unsuspecting",
    "Unsuspicious",
    "Unsympathetic",
    "Unsystematic",
    "Unusual",
    "Unwilling",
    "Unworried",
    "Upbeat",
    "Upset",
    "Uptight",
    "Useful",
    "Utilitarian",
    "Vacant",
    "Vague",
    "Vain",
    "Valiant",
    "Valorous",
    "Values fair competition",
    "Values family",
    "Values hard work",
    "Values honesty",
    "Values material possessions",
    "Values money",
    "Values religion",
    "Vehement",
    "Vengeful",
    "Venomous",
    "Venturesome",
    "Verbose",
    "Versatile",
    "Veteran",
    "Vicious",
    "Vigilant",
    "Vigorous",
    "Vindictive",
    "Violent",
    "Virtuous",
    "Visual",
    "Vital",
    "Vivacious",
    "Volatile",
    "Voracious",
    "Vulgar",
    "Vulnerable",
    "Wanton",
    "Warlike",
    "Warm",
    "Warm hearted",
    "Wary",
    "Wasteful",
    "Watchful",
    "Weak",
    "Weak nerves",
    "Weary",
    "Weepy",
    "Weird",
    "Welcoming",
    "Well grounded",
    "Well-groomed",
    "Whimsical",
    "Wholesome",
    "Wicked",
    "Wild",
    "Willful",
    "Willing",
    "Willpower",
    "Wise",
    "Wishy washy",
    "Withdrawn",
    "Witty",
    "Wonderful",
    "Works well under pressure",
    "Worldly",
    "Worried",
    "Worrying",
    "Worshipful",
    "Worships the devil",
    "Worthless",
    "Wretched",
    "Xenophobic",
    "Youthful",
    "Zany",
    "Zealot",
    "Zealous",
    "Able",
    "Accident prone",
    "Adorable",
    "Always hungry",
    "Beautiful",
    "Dirty",
    "Diseased",
    "Filthy",
    "Hardy",
    "Weak constitution",
    "Healthy",
    "Hormonal",
    "Ill",
    "Lean",
    "Nimble",
    "Obese",
    "Overweight",
    "Plain",
    "Sterile",
    "Tall",
    "Ugly",
    "Unclean",
    "Wealthy",
    "Young",
    "Abandoned",
    "Possessed",
    "Psychopath"
]

def randomNPCName():
    return "%BOSS " + random.choice(adjectives).title() + " " + random.choice(monsterNames).title() + ") "